import API_KEY from './api_key';
import { userRecipes } from './controller';

export const getRecipeById = async function (id) {
  try {
    const res = await fetch(
      `https://forkify-api.jonas.io/api/v2/recipes/${id}`
    );
    if (!res.ok) throw new Error('Error getting recipe');

    const recipeJSON = await res.json();
    const recipe = recipeJSON.data;
    return recipe;
  } catch (err) {
    console.error(err);
  }
};

const testRecipe = {
  publisher: 'Bencipe',
  ingredients: [
    {
      quantity: 1,
      unit: 'pound',
      description: 'fresh pizza dough',
    },
    {
      quantity: null,
      unit: '',
      description: 'Olive oil for brushing',
    },
    {
      quantity: 0.33,
      unit: 'cup',
      description: 'bbq sauce',
    },
    {
      quantity: 1,
      unit: 'cup',
      description: 'shredded cheddar cheese',
    },
    {
      quantity: 1,
      unit: 'cup',
      description: 'shredded cooked chicken',
    },
    {
      quantity: 0.5,
      unit: 'cup',
      description: 'roasted corn cut off the cob',
    },
    {
      quantity: 1,
      unit: '',
      description: 'red onion thinly sliced',
    },
    {
      quantity: 0.5,
      unit: 'cup',
      description: 'halved cherry tomatoes',
    },
    {
      quantity: null,
      unit: '',
      description: 'Small handful of cilantro',
    },
    {
      quantity: null,
      unit: '',
      description: 'Small handful of chopped green onions',
    },
    {
      quantity: null,
      unit: '',
      description: 'Kosher salt and freshly cracked black pepper to taste',
    },
  ],
  source_url: 'http://whatsgabycooking.com/grilled-bbq-chicken-pizza/',
  image_url: 'http://forkify-api.herokuapp.com/images/IMG_15866d21.jpg',
  title: 'Test Recipe',
  servings: 4,
  cooking_time: 60,
  id: 'TESTID123',
};

// TODO: Make userRecipes data persist for the browser
// This works. Note that the id is generated by the API. I probably want to maintain a mapping of user-generated recipe names and ids so I can add the user-gen symbol
// Note that the POST request will fail if the URL and Image URL are not valid.
export const sendPostRequest = async function (requestBody) {
  const bodyJSON = JSON.stringify(requestBody);
  const settings = {
    method: 'POST',
    body: bodyJSON,
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
  };
  try {
    const fetchResponse = await fetch(
      `https://forkify-api.jonas.io/api/v2/recipes?&key=${API_KEY}`,
      settings
    );

    if (!fetchResponse.ok) throw new Error('Error submitting recipe');

    const data = await fetchResponse.json();
    userRecipes.push(data.data.recipe.id);
    console.log(userRecipes);
    return data.data;
  } catch (err) {
    console.error(err);
  }
};

//sendPostRequest(testRecipe);
